# coding: utf-8

"""
    Language Explorer API

    OpenAPI specification for the Language Explorer API.

    The version of the OpenAPI document: 0.1.0
    Contact: kttpsy@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from src.utils.openapi_client.models.css_language_parameters import CSSLanguageParameters
from src.utils.openapi_client.models.taco_expression_language_params import TacoExpressionLanguageParams
from src.utils.openapi_client.models.taco_schedule_language_params import TacoScheduleLanguageParams
from typing import Optional, Set
from typing_extensions import Self

class GenerateParams(BaseModel):
    """
    Parameters supplied to the API for generating one or more programs with the provided language and expander to create said program.
    """ # noqa: E501
    count: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="Specify the number of programs to generate.")
    css: Optional[CSSLanguageParameters] = Field(default=None, description="Parameters for CSS Language.")
    nft: Optional[Dict[str, Any]] = Field(default=None, description="Parameters for NFTables language.")
    return_edge_lists: Optional[StrictBool] = Field(default=None, description="Toggle whether to return edge lists along with each graph.")
    return_features: Optional[StrictBool] = Field(default=None, description="Toggle whether to return WL-kernel extracted features along with each graph.")
    return_grammar: Optional[StrictBool] = Field(default=None, description="Toggle whether to return the grammar in BNF form that was used to generate programs.")
    spice: Optional[Dict[str, Any]] = Field(default=None, description="Parameters for SPICE language.")
    spiral: Optional[Dict[str, Any]] = Field(default=None, description="Parameters for SPIRAL Language.")
    taco_expr: Optional[TacoExpressionLanguageParams] = Field(default=None, description="Parameters for Taco Expression Language.")
    taco_sched: Optional[TacoScheduleLanguageParams] = Field(default=None, description="Parameters for Taco Schedule Language.")
    wl_degree: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="Specify the number of WL-kernel iterations to be run with each graph to extract features.")
    __properties: ClassVar[List[str]] = ["count", "css", "nft", "return_edge_lists", "return_features", "return_grammar", "spice", "spiral", "taco_expr", "taco_sched", "wl_degree"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GenerateParams from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of css
        if self.css:
            _dict['css'] = self.css.to_dict()
        # override the default output from pydantic by calling `to_dict()` of taco_expr
        if self.taco_expr:
            _dict['taco_expr'] = self.taco_expr.to_dict()
        # override the default output from pydantic by calling `to_dict()` of taco_sched
        if self.taco_sched:
            _dict['taco_sched'] = self.taco_sched.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GenerateParams from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "count": obj.get("count"),
            "css": CSSLanguageParameters.from_dict(obj["css"]) if obj.get("css") is not None else None,
            "nft": obj.get("nft"),
            "return_edge_lists": obj.get("return_edge_lists"),
            "return_features": obj.get("return_features"),
            "return_grammar": obj.get("return_grammar"),
            "spice": obj.get("spice"),
            "spiral": obj.get("spiral"),
            "taco_expr": TacoExpressionLanguageParams.from_dict(obj["taco_expr"]) if obj.get("taco_expr") is not None else None,
            "taco_sched": TacoScheduleLanguageParams.from_dict(obj["taco_sched"]) if obj.get("taco_sched") is not None else None,
            "wl_degree": obj.get("wl_degree")
        })
        return _obj


