# coding: utf-8

"""
    Language Explorer API

    OpenAPI specification for the Language Explorer API.

    The version of the OpenAPI document: 0.1.0
    Contact: kttpsy@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class LanguageWrapper(str, Enum):
    """
    Enumeration of all supported languages currently within lang-explorer. This will almost certainly grow and change with time.
    """

    """
    allowed enum values
    """
    CSS = 'css'
    NFT = 'nft'
    SPIRAL = 'spiral'
    TACOEXPRESSION = 'tacoexpression'
    TACOSCHEDULE = 'tacoschedule'
    SPICE = 'spice'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of LanguageWrapper from a JSON string"""
        return cls(json.loads(json_str))


