# coding: utf-8

"""
    Language Explorer API

    OpenAPI specification for the Language Explorer API.

    The version of the OpenAPI document: 0.1.0
    Contact: kttpsy@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self

class TacoScheduleLanguageParams(BaseModel):
    """
    Parameters for Taco Schedule Language.
    """ # noqa: E501
    divide_factor_variables: List[StrictStr]
    fused_index_variables: List[StrictStr]
    index_variables: List[StrictStr]
    split_factor_variables: List[StrictStr]
    unroll_factor_variables: List[StrictStr]
    workspace_index_variables: List[StrictStr]
    __properties: ClassVar[List[str]] = ["divide_factor_variables", "fused_index_variables", "index_variables", "split_factor_variables", "unroll_factor_variables", "workspace_index_variables"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TacoScheduleLanguageParams from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TacoScheduleLanguageParams from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "divide_factor_variables": obj.get("divide_factor_variables"),
            "fused_index_variables": obj.get("fused_index_variables"),
            "index_variables": obj.get("index_variables"),
            "split_factor_variables": obj.get("split_factor_variables"),
            "unroll_factor_variables": obj.get("unroll_factor_variables"),
            "workspace_index_variables": obj.get("workspace_index_variables")
        })
        return _obj


